### ISSUE TITLE
Superscript and subscript features

### ISSUE THREAD

**Issue by skalyan91** [Fuzzypeg/Coelacanth#5]
Please add the `subs` and `sups` features. I would like to be able to create proper footnote markers in CSS (and XeLaTeX), but this isn’t possible without the right OpenType features.

Thanks for creating these fonts! They fulfil a childhood dream of mine.

**Comment by Fuzzypeg** [comment]
I've found in LaTeX that subscript and superscript give good results if I'm using optical weights: rather than use purpose-build subscript/superscript glyphs from within the same font, it will use glyphs from a smaller optical size variant. This is what the optical sizes were intended for.
This repo is moving to https://gitlab.com/Fuzzypeg/coelacanth. If you still have issues with superscript/subscript, then feel free to open a new ticket there.
